# Generated by Django 2.1 on 2018-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生信息'},
        ),
    ]
